# Generated by Django 5.1.6 on 2025-04-26 19:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='place_of_work',
            field=models.CharField(blank=True, max_length=256, validators=[django.core.validators.RegexValidator('^[a-zA-Zа-яА-ЯёЁіІїЇєЄґҐ0-9_. -]+$', 'Text can contain letters (latin/cyrillic), numbers, underscores, dots, dashes and spaces')], verbose_name='place of work'),
        ),
    ]
