# Generated by Django 5.1.2 on 2024-11-10 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='age'),
        ),
        migrations.AddField(
            model_name='user',
            name='logged_in',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='user',
            name='place_of_work',
            field=models.CharField(blank=True, max_length=256, verbose_name='place of work'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_edited',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last profile edit'),
        ),
        migrations.AddField(
            model_name='user',
            name='task_n_completed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last task completed'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, default=380000000009, max_length=15, verbose_name='phone number'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
