# Generated by Django 5.1.9 on 2025-05-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_place_of_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Email must be unique and is used for login', max_length=254, unique=True, verbose_name='email'),
        ),
    ]
