# Generated by Django 5.1.2 on 2024-12-03 11:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_category_name_alter_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(blank=True, help_text='Age must be between 6 and 100 years', null=True, validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(100)], verbose_name='age'),
        ),
    ]
