# Generated by Django 5.1.6 on 2025-02-27 15:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_category_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='logged_in',
            new_name='last_login_at',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='profile_edited',
            new_name='last_profile_edit_at',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='task_n_completed',
            new_name='last_task_completed_at',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Zа-яА-ЯёЁіІїЇєЄґҐ0-9_. -]+$', 'This field can contain letters (latin/cyrillic), numbers, underscores, dots, dashes, and spaces')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='place_of_work',
            field=models.CharField(blank=True, max_length=256, validators=[django.core.validators.RegexValidator('^[a-zA-Zа-яА-ЯёЁіІїЇєЄґҐ0-9_. -]+$', 'This field can contain letters (latin/cyrillic), numbers, underscores, dots, dashes, and spaces')], verbose_name='place of work'),
        ),
    ]
