# Generated by Django 5.1.6 on 2025-03-10 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_category_alter_task_category_project_task_project'),
        ('users', '0010_alter_category_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
