# Generated by Django 5.1.6 on 2025-04-12 14:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator('^\\+\\d{7,15}$', "The phone number must start with '+' and contain 7 to 15 digits only after it")], verbose_name='phone number'),
        ),
    ]
