# Generated by Django 5.1.6 on 2025-04-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsharelink',
            name='max_uses',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of uses. Leave blank for unlimited uses', null=True),
        ),
    ]
