# Generated by Django 5.1.6 on 2025-04-26 19:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_projectsharelink_max_uses'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsharelink',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=128, validators=[django.core.validators.RegexValidator('^[a-zA-Zа-яА-ЯёЁіІїЇєЄґҐ0-9_. -]+$', 'Text can contain letters (latin/cyrillic), numbers, underscores, dots, dashes and spaces')]),
        ),
    ]
