# Generated by Django 5.1.2 on 2024-11-11 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_favorite',
            field=models.BooleanField(default=False, verbose_name='Favorite'),
        ),
    ]
