# Generated by Django 5.1.2 on 2024-11-27 23:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_task_description_alter_task_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9_. -]+$', 'Title can only contain letters, numbers, underscores, dots, dashes, and spaces')]),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9_. -]+$', 'Title can only contain letters, numbers, underscores, dots, dashes, and spaces')]),
        ),
    ]
