# Generated by Django 5.1.6 on 2025-02-27 15:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_task_options_alter_task_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, validators=[django.core.validators.RegexValidator('^[a-zA-Zа-яА-ЯёЁіІїЇєЄґҐ0-9_. -]+$', 'Text can contain letters (latin/cyrillic), numbers, underscores, dots, dashes, and spaces')]),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[a-zA-Zа-яА-ЯёЁіІїЇєЄґҐ0-9_. -]+$', 'Text can contain letters (latin/cyrillic), numbers, underscores, dots, dashes, and spaces')]),
        ),
    ]
