name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10, 3.11, 3.12]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up PostgreSQL database (if you're using PostgreSQL)
      uses: shivammathur/setup-postgresql@v2
      with:
        postgresql-version: '17'
      env:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password
        POSTGRES_DB: test_db

    - name: Wait for PostgreSQL to be ready
      run: |
        sudo apt-get install -y netcat
        until nc -z -v -w30 localhost 5432; do
          echo "Waiting for PostgreSQL..."
          sleep 1
        done

    - name: Run Migrations
      run: |
        python manage.py migrate

    - name: Run Tests
      run: |
        python manage.py test --noinput api.tests  # Avoids the need for user input during test runs

    - name: Collect Static Files (optional, useful for deployment)
      run: |
        python manage.py collectstatic --noinput